version: '3.9'

services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: WN+_e^+a5bJ46EE
    ports:
      - 3306:3306      