version: '3'

services:
  mysql:
    image: arm64v8/mysql:oracle
    container_name: mysql-apple-silicon
    ports:
      - 3306:3306
    volumes:
     - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=dbadmin
      - MYSQL_PASSWORD=AdWvA6Ln      
    deploy:
      resources:
        limits:
          memory: 1024M